### ISSUE TITLE
Windwos11在使用终端的情况下使用status出现报错

### ISSUE THREAD

**Issue by BakaReimu** [LazyAlienServer/MirrorMcsmcdR#10]
报错显示：
> !!mirror status
[MCDR] [04:47:54] [TaskExecutor/ERROR]: Error when executing command '!!mirror status', source=ConsoleCommandSource(info_id=2491), node=Literal(literals={'!!mirror'}), plugin=PackedPlugin(state=<PluginState.READY: 4>, path=WindowsPath('plugins/MirrorMcsmcdR-v1.3.2.mcdr')), for='command callback', path="[Literal '!!mirror', Literal 'status']"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 355, in __smart_callback
    return callback(*call_args)
           ^^^^^^^^^^^^^^^^^^^^
  File "plugins\MirrorMcsmcdR-v1.3.2.mcdr\mirror_mcsmcdr\mirror_manager.py", line 191, in sub_wrapper
    return func(self, source, context, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\MirrorMcsmcdR-v1.3.2.mcdr\mirror_mcsmcdr\mirror_manager.py", line 215, in status
    status_code = self.server_api.status()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\MirrorMcsmcdR-v1.3.2.mcdr\mirror_mcsmcdr\utils\server_utils.py", line 42, in status
    return self.system.status() if self.system else "unavailable"
           ^^^^^^^^^^^^^^^^^^^^
  File "plugins\MirrorMcsmcdR-v1.3.2.mcdr\mirror_mcsmcdr\utils\api\system_api.py", line 19, in status
    return self.system_api.status()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\MirrorMcsmcdR-v1.3.2.mcdr\mirror_mcsmcdr\utils\api\system_api.py", line 79, in status
    for pid in set(re.findall(":30001.*?([0-9]+)\n"), text):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: findall() missing 1 required positional argument: 'string'

我应该怎么样解决它

**Comment by tanhHeng** [comment]
这是一个bug（
感谢提交，已在`v1.3.3`修复 #11
